### ISSUE TITLE
Plugin doesn't show any subtitle

### ISSUE THREAD

**Issue by GonESI** [ElHappy/service.subtitles.tusubtitulo#1]
I have checked with many chapters of different series the plugin does not show subtitles as a result, whereas others subtitle services do (05/05/2016).

I do not know why but it may be caused by the final download url, which might have changed.

Greetings and thanks for your time.

**Comment by ElHappy** [comment]
Now it's fixed and is working again, sorry for not noticed sooner.

And thanks for informing.

Greetings.
