### ISSUE TITLE
issue is back

### ISSUE THREAD

**Issue by stevendom1987** [ElHappy/service.subtitles.tusubtitulo#2]
the same issue reported 5 days ago seems to be happening again. thanks!

**Comment by ElHappy** [comment]
I've sent the changes to the addons git of kodi.tv, but they haven't answered yet, I hope they can answer soon. If you want to test or use it, can clone the git project in your addons folder (you need to delete the previous version).

Greetings.

**Comment by fedex-bermu** [comment]
I'm having the same problem, not finding anything with new version.

**Comment by ElHappy** [comment]
I fixed new errors in version 1.0.5, but isn't yet in the addons git of kodi.tv, I still waiting they answer. If you want to test or use it the new version, can clone the git project in your addons folder (you need to delete the previous version).

Greetings.

Repare nuevos errores en la versión 1.0.5, pero todavía no está en el git de addons de kodi.tv, sigo esperando que contesten. Si deseas probar o utilizar la nueva versión, se puede clonar el proyecto git en la carpeta de addons (es necesario eliminar la versión anterior).

Saludos.

**Comment by fedex-bermu** [comment]
Ver 1.0.5 still no results.

22:06:27 T:3764   DEBUG: Thread LanguageInvoker 3764 terminating
22:06:27 T:9648   DEBUG: ### [SEARCHSTRING] - serie/Suits/5/11/*
22:06:27 T:9648   DEBUG: ### [PROXY] - Proxy disabled
22:06:29 T:9648   DEBUG: ### [SEARCHSTRING] - serie/Suits/5/11/*
22:06:29 T:9648   DEBUG: Previous line repeats 3 times.
22:06:29 T:9648    INFO: CPythonInvoker(119, C:\Users\FedeX\AppData\Roaming\Kodi\addons\service.subtitles.tusubtitulo-master\service.py): script successfully run
22:06:29 T:7228   DEBUG: XFILE::CPluginDirectory::WaitOnScriptResult- plugin returned successfully
22:06:30 T:9648    INFO: Python script stopped

**Comment by ElHappy** [comment]
Fixed (1.0.6), the site change again a parameter search, start working on a new way to take the subtitles.

Greetings.

Reparado (1.0.6), el sitio cambio otra vez un parámetro de búsqueda, inicio a trabajar en una nueva forma de tomar los subtítulos.

Saludos.

**Comment by fedex-bermu** [comment]
Great, now working for almost all shows. Although is not working for some reason with some shows like 12 Monkeys, I dont know if I should open a new issue or keep it in this one.

**Comment by Jadeka** [comment]
genial que actualizaras este addon y mejor aun que estés trabajando en una mejor manera de obtener los subtitulos ya que algunas series por algún motivo no descargan subtitulos, seria bueno que pudieras revisar este inconveniente en mi experiencia con Lucifer, dc legends of tomorrow o 12 monos los subtitulos no cargan. Por todo lo demás es muy bueno tu aporte y tu trabajo lo agradezco muchísimo, lo uso todo el tiempo por encima de otros buscadores de sub.

Saludos,

**Comment by risoterapia** [comment]
Lo acabo de poner (he desinstalado antes la versión 1.0.5 y he instalado esta desde .zip directamente y no me encuentra subtítulos en Juego de Tronos o Fear the walking Dead, así que supongo que no está arreglado correctamente.
Openelec última versión, Isengaard.

**Comment by ElHappy** [comment]
Han vuelto a cambiar en el sitio parámetros clave para la búsqueda de los subtítulos, sigo trabajando en una nueva forma de obtener los subtítulos para evitar los problemas con esos cambios después de reparar el addon.

Saludos.

**Comment by risoterapia** [comment]
Muchas gracias por tu sensacional y desinteresado trabajo!

**Comment by ElHappy** [comment]
Acabo de subir una nueva versión (1.0.7), y agregado Lucifer a la lista de nombres alternativos. Espero que haya menos movimientos por parte del sitio para evitar buscar los subtítulos.

Saludos.

I just push a new version (1.0.7), and added Lucifer to the list of alternative names. I hope there's less movement by the site to avoid searching the subtitles.

Greetings.

**Comment by Jadeka** [comment]
Que bueno hermano, probado y funcionando, de verdad que buen trabajo, esperemos que el sitio no de mas dolores de cabeza. Y gracias por la adición de Lucifer espero q para una próxima versión puedas revisar también Legends of Tomorrow, Gracias por tu tiempo y dedicación.

**Comment by methodmann** [comment]
Ahora probare alguna que otra serie pero con the flash no me funciona. Pone revise la información de registro.  Gracias por el trabajazo que haces

**Comment by risoterapia** [comment]
He bajado la nueva versión desde clone or download y me dice que no es válida para instalar como zip (estructura no compatible). Luego borro la carpeta de addons y vuelvo a poner extraída la del 1.07 y lo reconoce como 1.06 pero veo en el changelog que es el 1.07 pero me da error y dice que mire el registro...

**Comment by ElHappy** [comment]
Si pueden pasen el nombre del plugin en donde ven las series, actualmente solo he probado sobre Exodus, y el nombre de la serie en donde falla (pero se funciona en otras series).

Saludos.

**Comment by methodmann** [comment]
Me falla usando quasar y specto fork de genesis y la serie the flash es la unica que he podido probar de momento.  Gracias

**Comment by Jadeka** [comment]
Falla en Exodus con Flash y DC Legends of tomorrow

**Comment by ElHappy** [comment]
Reparados los problemas con el enlace de subtítulos mas actualizados (1.0.8), lo valide en Flash, DC Legends of Tomorrow y otras series (desde Exodus), también agregue un nombre alternativo para Twelve Monkeys.

Después depuro con Quasar y Specto.

Saludos.

**Comment by Jadeka** [comment]
probado y me temo que no funciona, no descarga ningun subtitulo en español y cuando lo hace no funciona. (Probado en exodus)

Gracias por tu tiempo

**Comment by ManuelOliveras** [comment]
Mira se agradece todo el plugin hermano pero mejor pide permiso a la administrasion de la pagina men, te estaas matando por algo que si tuvieses el permiso de ellos no estuviera pasando a no ser que ellos vallan a lanzar su app y dos, otra cosa, kodi te va a bloquear el addon por muchas actualizasiones que estas mandando. ellos tienen un tiempo entre actualizacion y si ven todos los cambios van a sacar el app por que entienden que no funcinoa. evitate problemas y haz las cosas como se deben. el exito de algo se desprende de hacer las cosas con un orden

**Comment by JacobMartinw** [comment]
I do not speak an excellent Spanish, but totally agreed with above comment. I remembered the first day the plugin passes to be "Unofficial" and then I realized that this is created without the auth. from the website and that won't help you. One because the users (like me) are tired of making updates all days, and second because you are making a script or program from a website that is obliviously doesn't want any script but them or something. Just do a new commit when you have something official. But I advise you to first make contact with the page. They can, also, contact Kodi and make a request to remove your plugin because they have not authorized it.

**Comment by ElHappy** [comment]
1- Reparada la toma de subtítulos (1.0.9).
2- Ya me comunique con los administradores desde el inicio y ofrecí apoyo a la construcción y mantenimiento del sitio, incluso apoyo en servidores, pero respondieron exigiendo eliminar el addon, me negué a eliminarlo porque es opensource. Eventualmente me aburriré de hacer cambios, pero hasta ahora ha sido entretenido el buscar como poder saltar los impedimentos. Solo disfruto programar.

Saludos.

1- Fixed take of subtitles (1.0.9).
2- I communicate with administrators from the beginning and offered support for the construction and maintenance of the site, including support on servers, but responded by demanding eliminate the addon, I refused to remove it because it's opensource. Eventually I'll bore to make changes, but so far has been entertaining the search to jump the impediments. I just enjoy programming.

Greetings.

**Comment by Jadeka** [comment]
De nuevo agradezco tu esfuerzo y dedicación, probando versión 1.0.9 y sigue sin funcionarme no se si estoy haciendo algo mal pero desinstalo e instalo la nueva versión y sigue sin cargarme subtitulos en español, probé con Arrow y legends of tomorrow en Exodus

**Comment by JacobMartinw** [comment]
It's not opensource, el_happy. If the website just tell you to remove it, you have to do that. That's go without the rules of an opensource app. You have to first have their permission. Sorry, but I  won't use this. Less knowing that you guys don't have the permission from website. How bad to read that.
