### ISSUE TITLE
Falla la lectura de idiomas

### ISSUE THREAD

**Issue by displaynone** [ElHappy/service.subtitles.tusubtitulo#4]
Hola

Soy usuario de tu plugin, veo que últimamente has estado actualizándolo, pero lleva unos días fallando, solo detecta inglés e incorrectamente.

Se debe a que han añadido un enlace raro dentro del <li>

He modificado tu código para que coja el segundo enlace, no sé si lo he hecho bien (aunque a mi me funciona) o si se puede hacer de otra forma mejor, no programo en python.

Te paso el código modificado:

```
    # Take link of subtitle
    if l.find('a', href=clear) != None and link == None:
      link = main_url + l.find_all('a', href=clear)[1].get('href')
      log("LINK", link)
```

Gracias por tu plugin :)

**Comment by ElHappy** [comment]
El problema es que los admins de tusubtitulo no quieren que se pueda descargar desde plugins sin acceder al sitio para poder descargarlos (y ver el banner de donaciones), han agregado enlaces ocultos para obstruir la detección. Y como hacían cambios al mismo tiempo que subía un parche, he decidido dejar de darle mantenimiento al plugin, agregue una expresión regular para diferenciar los enlaces (1.0.10), pero sin duda harán un cambio pronto, por lo que puedes hacer un fork e investigar la forma de poder obtener los enlaces para ti.

Como alternativa te recomiendo usar el plugin de subdivx.

Saludos.

**Comment by josecurioso** [comment]
Se que esto hace meses que nadie mira para ello pero hace unos dias me empeñe en automatizar la descarga de subtitulos de tusubtitulo. Resulta que para tocar las narices ahora al final de la URL añaden un número generado por ellos para cada serie. El caso es que ahora mismo tengo un script de python que descarga subtitulos automaticamente de la página pero no soy capaz de implementarlo como un addon de Kodi. Si todavía hay alguien que pueda interesado en hacerlo o  en explicarme el codigo del addon se lo puedo pasar.

Un Saludo

**Comment by ElHappy** [comment]
Que tal, creo que te refieres al numero de serie de subtitulo "nombre_serie/num_temporada/num_capitulo/num_subtitulo", ese numero siempre ha existido, pero no es del todo necesario, puedes sustituirlo con un asterisco y funcionara el sitio.

Saludos.

**Comment by josecurioso** [comment]
Gracias por responder, no se me había ocurrido probarlo pero lo del asterisco aligera mucho el proceso.

**Comment by alqantara** [comment]
Hola @josecurioso podrías decirme si obtuviste resultado con la modificación del plugin? Y donde podría probarlo?

Gracias!

**Comment by josecurioso** [comment]
Nada @bolxevike en su día no fui capaz y me quedé solo con la aplicación de escritorio que funciona mas o menos xD 
De todas formas si en un futuro vuelvo a ello aviso por aquí

**Comment by josecurioso** [comment]
Bueno, estoy de vuelta con el tema. No voy a explicar exactamente que arreglos le he hecho para que funcione (para evitar que lo desmonten) pero el caso es que ahora funciona tal cual lo tengo en mi repositorio. El nuevo plugin ya está esperando la aprobación del equipo de Kodi pero ayer por la tarde tusubtitulo.com se cayó tras una airada discusión de los administradores y por ahora no se sabe nada.
Si en algún momento vuelve a ir la página queda avisado que hice funcionar el plugin. 
Un saludo

**Comment by alqantara** [comment]
Pues en cuanto vuelvan, si lo hacen, volveré a probarlo y a ver si por una vez se dan cuenta que los subtitulos que se suben allí son para poderlos disfrutar, no para generarles trafico... Asco de ego digital...

Muchas gracias @josecurioso por el currazo!

**Comment by methodmann** [comment]
Hace unos días me funcionaba perfectamente pero hoy ya no. Gracias por tu
trabajo

**Comment by josecurioso** [comment]
@methodman es con todas las series o con una en concreto?, si es una me puedes decir cual?, lo miraré hoy por la tarde.

PD la próxima vez abre el error en mi repositorio y así dejamos este hilo ya cerrado

**Comment by methodmann** [comment]
Ahora mismo me esta pasando con todas. Le doy ala addon para que me muestre los subtitulos y me sale un error que dice "Revise la información de registro"
Gracias
