### ISSUE TITLE
Mantenimiento

### ISSUE THREAD

**Issue by ngosang** [ElHappy/service.subtitles.tusubtitulo#5]
Hola,
¿Cuál es el motivo por el que has dejado de mantener el plugin? Si no existe ningún problema técnico me gustaría continuar con el desarrollo.
Un saludo.

**Comment by ElHappy** [comment]
Deje de mantenerlo por el cambio constante de parte del administrador del sitio tusubtitulo para dificultar la busqueda y descarga, al no querer que se pueda descargar desde otra parte que no sea el sitio y no aceptan ayuda alguna para el desarrollo del sitio, plugins externos o servidores, a menos que sea por medio de un donativo.

Si gustas continuar con el desarrollo puedes hacer un fork sin problema de mi parte, solo ten en cuenta que pueden empezar una nueva ola de dificultar la búsqueda y descarga de subtítulos.

Saludos.
